### ISSUE TITLE
K-Means DBA clustering buffer issue

### ISSUE THREAD

**Issue by jmtatsch** [wannesm/dtaidistance#102]
Hello,

I tried the new K-Means DBA from the master like this:

```
model5 = clustering.KMeans(k=4, max_it=10, max_dba_it=10, dists_options={"window": 40}, )
cluster_idx, performed_it = model5.fit(series, use_c=True, use_parallel=False)
```
But I get this error:

```
Traceback (most recent call last):
  File "/home/tatsch/Workspace/error_pattern_recognition/curve_analysis.py", line 566, in <module>
    cluster_idx, performed_it = model5.fit(series, use_c=True, use_parallel=False)
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/clustering/kmeans.py", line 262, in fit
    clusters_distances = list(map(fn, [(self.series[idx], self.means, self.dists_options) for idx in
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/clustering/kmeans.py", line 66, in _distance_c_with_params
    d = dtw_cc.distance(series, mean, **dists_options)
  File "dtaidistance/dtw_cc.pyx", line 248, in dtaidistance.dtw_cc.distance
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
```
My series is of shape (10, 291)

Any idea what I am doing wrong?

**Comment by wannesm** [comment]
The DBA functionality was not yet very stable. I just pushed an update to master that fixes some issues. Can you try again?

**Comment by jmtatsch** [comment]
Uninstalled old package, updated to latest master, rebuilt, installed.

with use_c=True
```
Series shape (100, 291)
Traceback (most recent call last):
  File "/home/tatsch/Workspace/error_pattern_recognition/curve_analysis.py", line 566, in <module>
    cluster_idx, performed_it = model5.fit(series, use_c=True, use_parallel=False)
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/clustering/kmeans.py", line 254, in fit
    clusters_distances = list(map(fn, [(self.series[idx], self.means, self.dists_options) for idx in
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/clustering/kmeans.py", line 66, in _distance_c_with_params
    d = dtw_cc.distance(series, mean, **dists_options)
  File "dtaidistance/dtw_cc.pyx", line 256, in dtaidistance.dtw_cc.distance
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
```
with use_c=False
```
Series shape (100, 291)
Traceback (most recent call last):
  File "/home/tatsch/Workspace/error_pattern_recognition/curve_analysis.py", line 566, in <module>
    cluster_idx, performed_it = model5.fit(series, use_c=False, use_parallel=False)
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/clustering/kmeans.py", line 254, in fit
    clusters_distances = list(map(fn, [(self.series[idx], self.means, self.dists_options) for idx in
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/clustering/kmeans.py", line 54, in _distance_with_params
    d = distance(series, avg, **dists_options)
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2-py3.8-linux-x86_64.egg/dtaidistance/dtw.py", line 218, in distance
    d = (s1[i] - s2[j])**2
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py", line 231, in __pow__
    return matrix_power(self, other)
  File "<__array_function__ internals>", line 5, in matrix_power
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 621, in matrix_power
    _assert_stacked_square(a)
  File "/home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 204, in _assert_stacked_square
    raise LinAlgError('Last 2 dimensions of the array must be square')
numpy.linalg.LinAlgError: Last 2 dimensions of the array must be square
```

The same series seems to run fine with all your other clustering methods...
Are there any more expectations on the input series?

**Comment by wannesm** [comment]
Thank you for sharing additional details.

Can you also share the numpy version you are using and type(series)?

The error seems because arrays are used at the inner level, which should be values. I can only reproduce a similar error when passing n-dimensional series instead of 1-dimensional series (kmeans currently only supports 1-dim). But since you have "Series shape (100, 291)", you are passing in a set of 100 1-dimensional series of length 291 and that should not be the problem.

**Comment by jmtatsch** [comment]
Type was the deprecated np.matrix and numpy was 1.19.4


`series = np.matrix(df_t, dtype=np.double)`

I replaced it with:

`series = df_t.to_numpy()`

and it seems to be working now.
Thank you for your help.

Bonus question:
How did you create this [plot](https://people.cs.kuleuven.be/~wannes.meert/dtw/kmeans.png?v=2)?

**Comment by wannesm** [comment]
Thanks. I've updated the code to be able to handle matrix (for as long it's still available).

**Comment by wannesm** [comment]
The plot is generated using the code in the unit-test: ``test_trace_kmeans`` in ``test_barycenter.py``:
https://github.com/wannesm/dtaidistance/blob/8f99c2960be5d3ebd4eba2715bbc7a0046876ce7/tests/test_barycenter.py#L142
