### ISSUE TITLE
Plotting fails with uneven-length time series

### ISSUE THREAD

**Issue by Komodovaran** [wannesm/dtaidistance#18]
The linkage tree plot will fail, due to a bug in the module `clustering.py`, line 227. Numpy doesn't know what to do with series of uneven lengths when calculating the max.

The easiest solution is to concatenate the arrays first, and then continue:
```
all_y = np.concatenate(self.series)
max_y = max(all_y.max(), np.abs(all_y.min()))
```

**Comment by wannesm** [comment]
Thinking about it, this is solved by the SeriesContainer class. Can you provide a detailled error message? And ideally, a minimal example that triggers the bug?

**Comment by Komodovaran** [comment]
The following fails in Python 3.6:

```
from dtaidistance import dtw
from dtaidistance import clustering
import numpy as np
import matplotlib.pyplot as plt

s1 = np.array([0., 0, 1, 2, 1, 0, 1, 0, 0, 2, 1, 0, 0])
s2 = np.array([0., 1, 2, 3, 1, 0, 0, 0, 2, 1, 0, 0])

series = s1,s2

m = clustering.LinkageTree(dtw.distance_matrix, {})
m.fit(series)

m.plot()
plt.show()
```

And throws

```
Traceback (most recent call last):
  File "/Users/Joh/Library/Preferences/PyCharmCE2018.2/scratches/scratch_13.py", line 14, in <module>
    m.plot()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dtaidistance/clustering.py", line 227, in plot
    max_y = max(np.max(self.series), abs(np.min(self.series)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2320, in amax
    out=out, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: operands could not be broadcast together with shapes (13,) (12,) 
```

**Comment by wannesm** [comment]
Numpy.max cannot deal with arrays with different lengths. We now check this first and use a different max function. See commit a283c6c78a22ad1c9e5a1b7e134157973a711957.
