### ISSUE TITLE
basic clustering example fails with "AttributeError: 'NoneType' object has no attribute 'shape'"

### ISSUE THREAD

**Issue by watsaqat** [wannesm/dtaidistance#26]
dynamicTimeWarping.py:

```
from dtaidistance import dtw
from dtaidistance import clustering
import numpy as np

s = np.array([
         [0, 0, 1, 2, 1, 0, 1, 0, 0],
         [0, 1, 2, 0, 0, 0, 0, 0, 0],
         [1, 2, 0, 0, 0, 0, 0, 1, 1],
         [0, 0, 1, 2, 1, 0, 1, 0, 0],
         [0, 1, 2, 0, 0, 0, 0, 0, 0],
         [1, 2, 0, 0, 0, 0, 0, 1, 1],
         [1, 2, 0, 0, 0, 0, 0, 1, 1]])
         

model = clustering.Hierarchical(dtw.distance_matrix_fast, {})
modelw = clustering.HierarchicalTree(model)
cluster_idx = modelw.fit(s)
modelw.plot("hierarchy.png")
```

error logs:
```
(timeSeriesClassification) bash-3.2$ python3 dynamicTimeWarping.py
The compiled dtaidistance C library is not available.
See the documentation for alternative installation options.
Traceback (most recent call last):
  File "dynamicTimeWarping.py", line 17, in <module>
    cluster_idx = modelw.fit(s)
  File "/Users/user/.local/share/virtualenvs/timeSeriesClassification-ight38Tz/lib/python3.7/site-packages/dtaidistance/clustering.py", line 418, in fit
    result = self._model.fit(series, *args, **kwargs)
  File "/Users/user/.local/share/virtualenvs/timeSeriesClassification-ight38Tz/lib/python3.7/site-packages/dtaidistance/clustering.py", line 73, in fit
    pbar = tqdm(total=dists.shape[0])
AttributeError: 'NoneType' object has no attribute 'shape'
```

I should note that this fails the same way if I run the clustering tests included in this repo as well

**Comment by wannesm** [comment]
You are requesting the C-library (distance_matrix_fast) but it is not available (see line 1 of your output). Maybe try compiling it again? We'll make the absence of the library throw an error instead of just printing it to make this more clear.

**Comment by watsaqat** [comment]
re-compiling worked. From the docs it sounded to me like there would only be a performance degradation if the c-lib wasn't installed, but it looks like it breaks functionality.

**Comment by wannesm** [comment]
That is only true for the distance_matrix function. Not for the distance_matrix_fast function.
