### ISSUE TITLE
Cannot import dtaidistance (indent error in code)

### ISSUE THREAD

**Issue by mike-schwarz** [wannesm/dtaidistance#45]
Getting this error. Seems like just a syntax thing

Traceback (most recent call last):

  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-70d4f7673b08>", line 70, in <module>
    from dtaidistance import dtw

  File "/opt/conda/lib/python3.6/site-packages/dtaidistance/__init__.py", line 19, in <module>
    from . import dtw

  File "/opt/conda/lib/python3.6/site-packages/dtaidistance/dtw.py", line 23
    s    from . import dtw_c
    ^
IndentationError: expected an indented block

**Comment by drean-possible** [comment]
![image](https://user-images.githubusercontent.com/34496841/58849744-21c55700-86be-11e9-8579-cd1457619a69.png)

**Comment by wannesm** [comment]
Correct, that should not be in there. It’s fixed and will soon be in pypi.
