### ISSUE TITLE
numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

### ISSUE THREAD

**Issue by Huii** [wannesm/dtaidistance#47]
I get the following error whenever I attempt to run DTW:

`numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`

The traceback looks as follows:
```
Traceback (most recent call last):
  File "D:\Projects\MyProject\Main.py", line 3, in <module>
    import Algorithms
  File "D:\Projects\MyProject\Algorithms.py", line 3, in <module>
    from dtaidistance import dtw, dtw_visualisation as dtwvis, clustering
  File "D:\Programs\Anaconda\Anaconda\lib\site-packages\dtaidistance-1.1.4-py3.6-win-amd64.egg\dtaidistance\__init__.py", line 19, in <module>
    from . import dtw
  File "D:\Programs\Anaconda\Anaconda\lib\site-packages\dtaidistance-1.1.4-py3.6-win-amd64.egg\dtaidistance\dtw.py", line 23, in <module>
    from . import dtw_c
  File "__init__.pxd", line 918, in init dtaidistance.dtw_c
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
The system I'm using is Windows 10.

P.S: I wrote before that all current errors are fixed for me but apparently I was still somehow using an older version. Sorry for the confusion.

**Comment by Huii** [comment]
Ok, the problem was on my side this time. I upgraded my numpy package and the error is gone. Thank you again for this great piece of software.
