### ISSUE TITLE
problem on import dtaidistance

### ISSUE THREAD

**Issue by jzicker** [wannesm/dtaidistance#7]
when I tried to import dtaidistance I got this error
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-12-7880e38fdd4e>", line 1, in <module>
    import dtaidistance as dtw

  File "/opt/workbench/users/jzicker/.local/lib/python3.5/site-packages/dtaidistance/__init__.py", line 19, in <module>
    from . import dtw

  File "/opt/workbench/users/jzicker/.local/lib/python3.5/site-packages/dtaidistance/dtw.py", line 17, in <module>
    from .util import SeriesContainer, dtaidistance_dir

  File "/opt/workbench/users/jzicker/.local/lib/python3.5/site-packages/dtaidistance/util.py", line 36
    logger.debug(f"Using directory: {directory}")
                                               ^
SyntaxError: invalid syntax

**Comment by wannesm** [comment]
Some Python 3.6 only syntax was used. I have changed it to <3.6 syntax and should work again.
