### ISSUE TITLE
issue finding dtw_c.pyx 

### ISSUE THREAD

**Issue by ns3115neha** [wannesm/dtaidistance#76]
I get error very similar to issue number 23 raised 

C:\pythoToMyPython\python.exe D:\pathToDtaidistance\dtaidistance\setup.py build_ext --inplace
on my Windows (10) machine, I get the following message:

Traceback (most recent call last):
File "D:\pathToDtaidistance\dtaidistance\setup.py", line 123, in
extra_link_args=extra_link_args)])
File "D:\PathToMyAnaconda\Anaconda\lib\site-packages\Cython\Build\Dependencies.py", line 897, in cythonize
aliases=aliases)
File "D:\PathToMyAnaconda\Anaconda\lib\site-packages\Cython\Build\Dependencies.py", line 777, in create_extension_list
for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
File "D:\PathToMyAnaconda\Anaconda\lib\site-packages\Cython\Build\Dependencies.py", line 102, in nonempty
raise ValueError(error_msg)
ValueError: 'dtaidistance/dtw_c.pyx' doesn't match any files

That's strange because my dtaidistance folder contains a file named "dtw_c.pyx"

**Comment by Huii** [comment]
Did you try running the setup.py file from within the dtaidistance directory (thus where the setup.py file is). The paths are defined relatively from the setup.py parent Directory. (See issue #23).

I still agree with @wannesm that this is something "that could be improved". ;)

**Comment by wannesm** [comment]
I now realize that the path is probably not a valid Windows path ("/" vs "\"). I have changed all paths to pathlib.Path instances, which should be platform independent.
